<?php
// xrayresource.module

///**
// * Implements hook_entity_info().
// */
function xrayresource_entity_info() {
    return array(
        'xray' => array(
            'label' => t('xray'),
            'base table' => 'xrays',
            'entity keys' => array(
                'id' => 'id',
            ),
            'entity class'           => 'Entity',
            'controller class'       => 'XrayController',
        ),
    );
}


//mention_reindex($entity->id, "post", html_entity_decode(strip_tags($entity->text)));


class XrayController extends EntityAPIController {

    public function load($ids = array(), $conditions = array()) {
        $entities = parent::load($ids, $conditions);

        foreach($entities as &$entity) {
            $entity->mentions = mention_load_from_content($entity->id, "xray");
        }
        return $entities;

    }
    public function save($entity, DatabaseTransaction $transaction = NULL) {
        parent::save($entity, $transaction);

//        $entity['test'] = "is this working?";
        // Scan the text for mentions
        $entity->mentions = mention_reindex($entity->id, "xray", html_entity_decode(strip_tags($entity->description)));

    }
}


function xray_load($id, $reset = FALSE) {
    return reset(xray_load_multiple(array($id), $reset));
}
function xray_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    return array_values(entity_load('xray', $ids, $conditions, $reset));
}
function xray_save($entity) {
    entity_save('xray', $entity);
}
function xray_delete($id) {
    entity_delete('xray', $id);
}


/**
 * Implementation of hook_services_resources().
 */
function xrayresource_services_resources() {
    return array(
        'xray' => array(
            'retrieve' => array(
                'help' => 'Retrieves a xray',
                'file' => array('file' => 'inc', 'module' => 'xrayresource'),
                'callback' => '_xray_resource_retrieve',
                'access callback' => '_xray_resource_access',
                'access arguments' => array('view'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'id',
                        'type' => 'int',
                        'description' => 'The id of the xray to get',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                ),
            ),
            'create' => array(
                'help' => 'Creates a xray',
                'file' => array('file' => 'inc', 'module' => 'xrayresource'),
                'callback' => '_xray_resource_create',
                'access callback' => '_xray_resource_access',
                'access arguments' => array('create'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'data',
                        'type' => 'struct',
                        'description' => 'The xray object',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                ),
            ),
            'update' => array(
                'help' => 'Updates a xray',
                'file' => array('file' => 'inc', 'module' => 'xrayresource'),
                'callback' => '_xray_resource_update',
                'access callback' => '_xray_resource_access',
                'access arguments' => array('update'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'id',
                        'type' => 'int',
                        'description' => 'The id of the node to update',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'data',
                        'type' => 'struct',
                        'description' => 'The xray data object',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                ),
            ),
            'delete' => array(
                'help' => 'Deletes a xray',
                'file' => array('file' => 'inc', 'module' => 'xrayresource'),
                'callback' => '_xray_resource_delete',
                'access callback' => '_xray_resource_access',
                'access arguments' => array('delete'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'nid',
                        'type' => 'int',
                        'description' => 'The id of the xray to delete',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                ),
            ),
            'index' => array(
                'help' => 'Retrieves a listing of xrays',
                'file' => array('file' => 'inc', 'module' => 'xrayresource'),
                'callback' => '_xray_resource_index',
                'access callback' => '_xray_resource_access',
                'access arguments' => array('index'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'page',
                        'optional' => TRUE,
                        'type' => 'int',
                        'description' => 'The zero-based index of the page to get, defaults to 0.',
                        'default value' => 0,
                        'source' => array('param' => 'page'),
                    ),
                    array(
                        'name' => 'fields',
                        'optional' => TRUE,
                        'type' => 'string',
                        'description' => 'The fields to get.',
                        'default value' => '*',
                        'source' => array('param' => 'fields'),
                    ),
                    array(
                        'name' => 'parameters',
                        'optional' => TRUE,
                        'type' => 'array',
                        'description' => 'Parameters array',
                        'default value' => array(),
                        'source' => array('param' => 'parameters'),
                    ),
                    array(
                        'name' => 'pagesize',
                        'optional' => TRUE,
                        'type' => 'int',
                        'description' => 'Number of records to get per page.',
                        'default value' => variable_get('services_node_index_page_size', 20),
                        'source' => array('param' => 'pagesize'),
                    ),
                ),
            ),
        ),
    );
}


