angular.module('directives',
    [
        'directives.ckeditor',
        'directives.mentions',
        'directives.gallery',
        'directives.lookup',
        'directives.patient_name',
        'directives.modal'
    ]);
