<?php
// consent_resource.module

///**
// * Implements hook_entity_info().
// */
function consent_resource_entity_info() {
    return array(
        'consentfile' => array(
            'label' => t('Consent Files'),
            'base table' => 'consent_files',
            'entity keys' => array(
                'id' => 'id',
            ),
            'entity class'           => 'Entity',
            'controller class'       => 'ConsentFileController',
        ),
    );
}


class ConsentFileController extends EntityAPIController {

    public function load($ids = array(), $conditions = array()) {
        $entities = parent::load($ids, $conditions);
        return $entities;
    }
}


function consentfile_load($id, $reset = FALSE) {
    return reset(consentfile_load_multiple(array($id), $reset));
}
function consentfile_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    $consent_files = array_values(entity_load('consentfile', $ids, $conditions, $reset));
    return $consent_files;
}
function consentfile_save($entity) {
    entity_save('consentfile', $entity);
}
function consentfile_delete($id) {
    entity_delete('consentfile', $id);
}


/**
 * Implementation of hook_services_resources().
 */
function consent_resource_services_resources() {
    $resources = array();

    $resources['consentfile'] = array(
        'retrieve' => array(
            'help' => 'Retrieves a consentfile',
            'file' => array('type' => 'inc', 'module' => 'consent_resource', 'name' => 'consent_resource_file'),
            'callback' => '_consent_resource_file_retrieve',
            'access callback' => '_consent_resource_file_access',
            'access arguments' => array('view'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the consent file to get',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'create' => array(
            'help' => 'Creates a consent file',
            'file' => array('type' => 'inc', 'module' => 'consent_resource', 'name' => 'consent_resource_file'),
            'callback' => '_consent_resource_file_create',
            'access callback' => '_consent_resource_file_access',
            'access arguments' => array('create'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The consent file object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'update' => array(
            'help' => 'Updates a consent file',
            'file' => array('type' => 'inc', 'module' => 'consent_resource', 'name' => 'consent_resource_file'),
            'callback' => '_consent_resource_file_update',
            'access callback' => '_consent_resource_file_access',
            'access arguments' => array('update'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the node to update',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The consent file data object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'delete' => array(
            'help' => 'Deletes a consent file',
            'file' => array('type' => 'inc', 'module' => 'consent_resource', 'name' => 'consent_resource_file'),
            'callback' => '_consent_resource_file_delete',
            'access callback' => '_consent_resource_file_access',
            'access arguments' => array('delete'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'nid',
                    'type' => 'int',
                    'description' => 'The id of the consent file to delete',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'index' => array(
            'help' => 'List all nodes',
            'file' => array('type' => 'inc', 'module' => 'consent_resource', 'name' => 'consent_resource_file'),
            'callback' => '_consent_resource_file_index',
            'access callback' => '_consent_resource_file_access',
            'access arguments' => array('index'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'page',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'The zero-based index of the page to get, defaults to 0.',
                    'default value' => 0,
                    'source' => array('param' => 'page'),
                ),
                array(
                    'name' => 'fields',
                    'optional' => TRUE,
                    'type' => 'string',
                    'description' => 'The fields to get.',
                    'default value' => '*',
                    'source' => array('param' => 'fields'),
                ),
                array(
                    'name' => 'parameters',
                    'optional' => TRUE,
                    'type' => 'array',
                    'description' => 'Parameters array',
                    'default value' => array(),
                    'source' => array('param' => 'parameters'),
                ),
                array(
                    'name' => 'pagesize',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'Number of records to get per page.',
                    'default value' => variable_get('services_node_index_page_size', 20),
                    'source' => array('param' => 'pagesize'),
                ),
            ),
        ),
    );

    return $resources;
}


