<?php
// patientresource.module

///**
// * Implements hook_entity_info().
// */
function patientresource_entity_info() {
    return array(
        'patient' => array(
            'label' => t('Patient'),
            'base table' => 'patients',
            'entity keys' => array(
                'id' => 'id',
            ),
            'entity class'           => 'Entity',
            'controller class'       => 'PatientController',
        ),
        'identifier' => array(
            'label' => t('Patient IDs'),
            'base table' => 'identifiers',
            'entity keys' => array(
                'id' => 'id',
            ),
            'entity class'           => 'Entity',
            'controller class'       => 'EntityAPIController',
        ),
        'address' => array(
            'label' => t('Address'),
            'base table' => 'addresses',
            'entity keys' => array(
                'id' => 'id',
            ),
            'entity class'           => 'Entity',
            'controller class'       => 'EntityAPIController',
        ),
    );
}


class PatientController extends EntityAPIController {

    protected function buildQuery($ids, $conditions = array(), $revision_id = FALSE) {
        $query = parent::buildQuery($ids, $conditions, $revision_id);

        // Specify additional fields from the user and node tables.
        $query->innerJoin('users', 'u', 'base.uid = u.uid');
        $query->addField('u', 'name', 'ownerName');
        return $query;
    }

    private function addRelated(&$entity) {
        $entity->user = user_load_small($entity->uid);

        // Add in the diagnoses
        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'diagnosis');
        $query->propertyCondition('patient_id', $entity->id);
        $result = $query->execute();
        $ids = array_keys($result['diagnosis']);
        $entity->diagnoses = diagnosis_load_multiple($ids);

        // Get the share count
        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'share');
        $query->propertyCondition('patient_id', $entity->id);
        $result = $query->execute();
        $ids = array_keys($result['share']);
        $entity->shares = share_load_multiple($ids);
        foreach($entity->shares as &$share) {
            $share->group = group_load($share->group_id);
        }

        // Tags
        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'tag_patient');
        $query->propertyCondition('patient_id', $entity->id);
        $result = $query->execute();

        $ids = array_keys($result['tag_patient']);

        $entity->patient_tags = tag_patient_load_multiple($ids);

        foreach($entity->patient_tags as &$patient_tag) {
            $patient_tag->tag = tag_load($patient_tag->tag_id);
        }
    }

    public function save($entity, DatabaseTransaction $transaction = NULL) {

        $old_patient = patient_load($entity['id']);
        if($entity['clinical_summary'] != $old_patient->clinical_summary) {
            $clinical_summary_changed = true;
        } else {
            $clinical_summary_changed = false;
        };


        parent::save($entity, $transaction);


        $entity->tag_patients = array();

        // analyse the clinical summary for terms
        if($clinical_summary_changed) {
            $recommendedTags = recommend_tags($entity['clinical_summary']);

            foreach($recommendedTags as $recommendedTag) {

                // do we have the tag?
                $query = new EntityFieldQuery();
                $query->entityCondition('entity_type', 'tag');

                $query->propertyCondition('uri', (string)$recommendedTag->term->concept->fullId);
                $result = $query->execute();
                $ids = array_keys($result['tag']);


                if(count($ids)) {
                    // that tag is in our system already
                    // Is the relationship there?
                    $query = new EntityFieldQuery();
                    $query->entityCondition('entity_type', 'tag_patient');
                    $query->propertyCondition('tag_id', $ids[0]);
                    $query->propertyCondition('patient_id', $entity['id']);
                    $result = $query->execute();
                    $tag_patient_ids = array_keys($result['tag_patient']);

                    if(count($tag_patient_ids)) {
                        // already exists, do nothing
                    } else {
                        // Now save the relationship
                        $tag_patient = new stdClass();
                        $tag_patient->patient_id = $entity['id'];
                        $tag_patient->tag_id = $ids[0];
                        $tag_patient->name = (string)$recommendedTag->term->name;
                        tag_patient_save($tag_patient);

                        // Give the tag back to the gui
                        $tag_patient->tag = tag_load($ids[0]);
                        $entity->tag_patients[] = $tag_patient;
                    }

                } else {

                    // create the tag
                    $tag = new stdClass();
                    $tag->name = (string)$recommendedTag->term->concept->preferredName;
                    $tag->uri = (string)$recommendedTag->term->concept->fullId;
                    $tag->ontology = "HPO";
                    tag_save($tag);

                    // Now save the relationship
                    $tag_patient = new stdClass();
                    $tag_patient->patient_id = $entity['id'];
                    $tag_patient->tag_id = $tag->id;
                    $tag_patient->name = (string)$recommendedTag->term->name;
                    tag_patient_save($tag_patient);
                }
            }
        }



        self::addRelated($entity);


    }

    public function load($ids = array(), $conditions = array()) {
        global $user;

        $entities = parent::load($ids, $conditions);

        foreach($entities as &$entity) {
            // check if the are the owner of this patient
            if($entity->uid != $user->uid) {
                // not the owner, remove private details
                unset(
                    $entity->first_name,
                    $entity->last_name,
                    $entity->alias,
                    $entity->dob,
                    $entity->gender,
                    $entity->ethnicity
                );
            }
            self::addRelated($entity);
        }



        return $entities;
    }

}


function patient_load($id, $reset = FALSE) {
    return reset(patient_load_multiple(array($id), $reset));
}
function patient_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    $patients = array_values(entity_load('patient', $ids, $conditions, $reset));
    return $patients;
}
function patient_save($entity) {
    entity_save('patient', $entity);
}
function patient_delete($id) {
    entity_delete('patient', $id);
}

function identifier_load($id, $reset = FALSE) {
    return reset(identifier_load_multiple(array($id), $reset));
}
function identifier_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    $identifier = array_values(entity_load('identifier', $ids, $conditions, $reset));
    return $identifier;
}
function identifier_save($entity) {
    entity_save('identifier', $entity);
}
function identifier_delete($id) {
    entity_delete('identifier', $id);
}

function address_load($id, $reset = FALSE) {
    return reset(address_load_multiple(array($id), $reset));
}
function address_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
    $address = array_values(entity_load('address', $ids, $conditions, $reset));
    return $address;
}
function address_save($entity) {
    entity_save('address', $entity);
}
function address_delete($id) {
    entity_delete('address', $id);
}


function patientresource_permission() {
    return array(
        'patient resource view any patient' => array(
            'title' => t('View Any Patient'),
        ),
        'patient resource create' => array(
            'title' => t('Create Patients'),
        )
    );
}


//function patientresource_field_access($op, $field, $entity_type, $entity, $account) {
//    echo "<div style='color:red; font-size:20px'>doing field access</div>";
//}
//
//
//echo "<pre>";
////print_r(entity_get_info());
////
//print_r(drupal_schema_fields_sql('patient'));
//
//$my_array = entity_load('patient');
//
//print_r($my_array);
//echo "<h1>field access</h1>";
//print_r(field_access('view', 'subject', 'patient'));
////
//echo "</pre>";

/**
 * Implementation of hook_services_resources().
 */
function patientresource_services_resources() {
    $resource = array();

    $resource['addresslookup'] = array(
        'index' => array(
            'help' => 'List all nodes',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_addresslookup'),
            'callback' => '_patientresource_addresslookup_index',
            'args' => array(
                array(
                    'name' => 'page',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'The zero-based index of the page to get, defaults to 0.',
                    'default value' => 0,
                    'source' => array('param' => 'page'),
                ),
                array(
                    'name' => 'fields',
                    'optional' => TRUE,
                    'type' => 'string',
                    'description' => 'The fields to get.',
                    'default value' => '*',
                    'source' => array('param' => 'fields'),
                ),
                array(
                    'name' => 'parameters',
                    'optional' => TRUE,
                    'type' => 'array',
                    'description' => 'Parameters array',
                    'default value' => array(),
                    'source' => array('param' => 'parameters'),
                ),
                array(
                    'name' => 'pagesize',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'Number of records to get per page.',
                    'default value' => variable_get('services_node_index_page_size', 20),
                    'source' => array('param' => 'pagesize'),
                ),
            ),
            'access arguments' => array('access content'),
        ),
    );

    $resource['address'] = array(
        'retrieve' => array(
            'help' => 'Retrieves a patient address',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_address'),
            'callback' => '_patientresource_address_retrieve',
            'access callback' => '_patientresource_address_access',
            'access arguments' => array('view'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the patient address to get',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'create' => array(
            'help' => 'Creates a address',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_address'),
            'callback' => '_patientresource_address_create',
            'access arguments' => array('patient resource create'),
            'access arguments append' => FALSE,
            'args' => array(
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The patient address object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'update' => array(
            'help' => 'Updates a address',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_address'),
            'callback' => '_patientresource_address_update',
            'access callback' => '_patientresource_address_access',
            'access arguments' => array('update'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the node to update',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The patient address data object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'delete' => array(
            'help' => 'Deletes a address',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_address'),
            'callback' => '_patientresource_address_delete',
            'access callback' => '_patientresource_address_access',
            'access arguments' => array('delete'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'nid',
                    'type' => 'int',
                    'description' => 'The id of the patient to delete',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'index' => array(
            'help' => 'List all nodes',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_address'),
            'callback' => '_patientresource_address_index',
            'args' => array(
                array(
                    'name' => 'page',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'The zero-based index of the page to get, defaults to 0.',
                    'default value' => 0,
                    'source' => array('param' => 'page'),
                ),
                array(
                    'name' => 'fields',
                    'optional' => TRUE,
                    'type' => 'string',
                    'description' => 'The fields to get.',
                    'default value' => '*',
                    'source' => array('param' => 'fields'),
                ),
                array(
                    'name' => 'parameters',
                    'optional' => TRUE,
                    'type' => 'array',
                    'description' => 'Parameters array',
                    'default value' => array(),
                    'source' => array('param' => 'parameters'),
                ),
                array(
                    'name' => 'pagesize',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'Number of records to get per page.',
                    'default value' => variable_get('services_node_index_page_size', 20),
                    'source' => array('param' => 'pagesize'),
                ),
            ),
            'access arguments' => array('access content'),
        ),
    );


    $resource['identifier'] = array(
        'retrieve' => array(
            'help' => 'Retrieves a patient identifier',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_identifier'),
            'callback' => '_patientresource_identifier_retrieve',
            'access callback' => '_patientresource_identifier_access',
            'access arguments' => array('view'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the patient identifier to get',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'create' => array(
            'help' => 'Creates a patient',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_identifier'),
            'callback' => '_patientresource_identifier_create',
            'access arguments' => array('patient resource create'),
            'access arguments append' => FALSE,
            'args' => array(
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The patient identifier object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'update' => array(
            'help' => 'Updates a patient',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_identifier'),
            'callback' => '_patientresource_identifier_update',
            'access callback' => '_patientresource_identifier_access',
            'access arguments' => array('update'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the node to update',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The patient identifier data object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'delete' => array(
            'help' => 'Deletes a patient',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_identifier'),
            'callback' => '_patientresource_identifier_delete',
            'access callback' => '_patientresource_identifier_access',
            'access arguments' => array('delete'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'nid',
                    'type' => 'int',
                    'description' => 'The id of the patient to delete',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'index' => array(
            'help' => 'List all nodes',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource_identifier'),
            'callback' => '_patientresource_identifier_index',
            'args' => array(
                array(
                    'name' => 'page',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'The zero-based index of the page to get, defaults to 0.',
                    'default value' => 0,
                    'source' => array('param' => 'page'),
                ),
                array(
                    'name' => 'fields',
                    'optional' => TRUE,
                    'type' => 'string',
                    'description' => 'The fields to get.',
                    'default value' => '*',
                    'source' => array('param' => 'fields'),
                ),
                array(
                    'name' => 'parameters',
                    'optional' => TRUE,
                    'type' => 'array',
                    'description' => 'Parameters array',
                    'default value' => array(),
                    'source' => array('param' => 'parameters'),
                ),
                array(
                    'name' => 'pagesize',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'Number of records to get per page.',
                    'default value' => variable_get('services_node_index_page_size', 20),
                    'source' => array('param' => 'pagesize'),
                ),
            ),
            'access arguments' => array('access content'),
        ),
    );


    $resource['patient'] = array(
        'retrieve' => array(
            'help' => 'Retrieves a patient',
            'file' => array('file' => 'inc', 'module' => 'patientresource'),
            'callback' => '_patientresource_retrieve',
            'access callback' => '_patientresource_access',
            'access arguments' => array('view'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the patient to get',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'create' => array(
            'help' => 'Creates a patient',
            'file' => array('file' => 'inc', 'module' => 'patientresource'),
            'callback' => '_patientresource_create',
            'access callback' => '_patientresource_access',
            'access arguments' => array(),
            'access arguments append' => FALSE,

//            'access arguments' => array('patient resource create'),
//            'access arguments append' => FALSE,
            'args' => array(
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The patient object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'update' => array(
            'help' => 'Updates a patient',
            'file' => array('file' => 'inc', 'module' => 'patientresource'),
            'callback' => '_patientresource_update',
            'access callback' => '_patientresource_access',
            'access arguments' => array('update'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'description' => 'The id of the node to update',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
                array(
                    'name' => 'data',
                    'type' => 'struct',
                    'description' => 'The patient data object',
                    'source' => 'data',
                    'optional' => FALSE,
                ),
            ),
        ),
        'delete' => array(
            'help' => 'Deletes a patient',
            'file' => array('file' => 'inc', 'module' => 'patientresource'),
            'callback' => '_patientresource_delete',
            'access callback' => '_patientresource_access',
            'access arguments' => array('delete'),
            'access arguments append' => TRUE,
            'args' => array(
                array(
                    'name' => 'nid',
                    'type' => 'int',
                    'description' => 'The id of the patient to delete',
                    'source' => array('path' => '0'),
                    'optional' => FALSE,
                ),
            ),
        ),
        'index' => array(
            'help' => 'List all nodes',
            'file' => array('type' => 'inc', 'module' => 'patientresource', 'name' => 'patientresource'),
            'callback' => '_patientresource_index',
            'args' => array(
                array(
                    'name' => 'page',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'The zero-based index of the page to get, defaults to 0.',
                    'default value' => 0,
                    'source' => array('param' => 'page'),
                ),
                array(
                    'name' => 'fields',
                    'optional' => TRUE,
                    'type' => 'string',
                    'description' => 'The fields to get.',
                    'default value' => '*',
                    'source' => array('param' => 'fields'),
                ),
                array(
                    'name' => 'parameters',
                    'optional' => TRUE,
                    'type' => 'array',
                    'description' => 'Parameters array',
                    'default value' => array(),
                    'source' => array('param' => 'parameters'),
                ),
                array(
                    'name' => 'pagesize',
                    'optional' => TRUE,
                    'type' => 'int',
                    'description' => 'Number of records to get per page.',
                    'default value' => variable_get('services_node_index_page_size', 200),
                    'source' => array('param' => 'pagesize'),
                ),
            ),
            'access arguments' => array('access content'),
        ),
    );

    return $resource;
}


