angular.module('directives.navigation',
    [
        'directives.navigation.menubar',
        'directives.navigation.sidemenu',
        'directives.navigation.submenubar',
        'directives.navigation.breadcrumbbar',
        'directives.navigation.loadingroute',
        'directives.navigation.menu_item'
    ]);
