angular.module('patient',
    [
        'patient.clinical_summary',
        'patient.genetic_reports',
        'patient.xrays',
        'patient.diagnoses',
        'patient.summary_dashboard',
        'patient.clinical_summary',
        'patient.contact_information',
        'patient.other_ids',
        'patient.consent',
        'patient.sharing',
        'patient.community',
        'patient.share'
    ]);
