angular.module('patients.patient',
    [
        'patient.clinical_summary',
        'patient.genetic_reports',
        'patient.xrays',
        'patient.diagnoses',
        'patient.summary',
        'patient.clinical_summary',
        'patient.contact_information',
        'patient.other_ids',
        'patient.consent',
        'patient.sharing',
        'patient.community',
        'patient.share',
        'patient.addresses'
    ]);
