<?php
// patient.module

/**
 * Gets a patient object by id
 *
 * @param $id
 */
function patient_get_patient($id) {
    $sql = "SELECT *
            FROM {patient}
            WHERE id=:id";
    return db_query($sql, array(":id" => $id))->fetchAll();
}

/**
 * Writes a patient to the database
 *
 * @param $patient
 */
function patient_write_patient($patient) {
    $primary_key = !empty($patient->id) ? array('id') : NULL;
    drupal_write_record('patient', $patient, $primary_key);
}

function patient_delete_patient($id) {
    $sql = "DELETE
            FROM {patient}
            WHERE id=:id";
    db_query($sql, array(":id" => $id));
}
